#!/bin/sh

xinput --set-prop "ETPS/2 Elantech Touchpad" "libinput Tapping Enabled" 1
xinput --set-prop "ETPS/2 Elantech Touchpad" "libinput Tapping Drag Enabled" 1
xinput --set-prop "ETPS/2 Elantech Touchpad" "libinput Tapping Drag Lock Enabled" 1

